# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G3sD0xmXoU-WMAi8RSF5bNZV6RKdpGBr
"""

from flask import Flask, request, jsonify
from flask_cors import CORS
import numpy as np
import tensorflow as tf

app = Flask(__name__)
model = tf.keras.models.load_model("ann_model.h5")

@app.route("/predict", methods=["POST"])
def predict():
    data = request.get_json()
    arr = np.array([data["values"]])
    arr = arr.reshape(-1, 28, 28)
    arr = arr.astype('float32') / 255.0
    pred = np.argmax(model.predict(arr))

    return jsonify({"prediction": int(pred)})

if __name__ == "__main__":
    app.run(debug=True, port=5002)

from flask import Flask, request, jsonify
import numpy as np
import tensorflow as tf

app = Flask(__name__)
model = tf.keras.models.load_model("ann_model.h5")

@app.route("/predict", methods=["POST"])
def predict():
        data = request.get_json()
        arr = np.array([data["values"]])
        arr = arr.reshape(-1, 28, 28)
        pred_digit = np.argmax(model.predict(arr))

        return jsonify({"prediction": int(pred_digit)})

if __name__ == "__main__":
    app.run(debug=True, port=5002)

