# -*- coding: utf-8 -*-
"""app_new.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11LGH0c_oHMIpoKi0FV8DGGEYa5ryiJEH
"""

from flask import Flask, request, jsonify
import numpy as np
import tensorflow as tf

app = Flask(__name__)

# 1. Load the Advanced CNN Model
# Ensure this filename matches what you saved earlier (e.g., "mnist_cnn_advanced.keras")
model = tf.keras.models.load_model("mnist_cnn_advanced.keras")

@app.route("/predict", methods=["POST"])
def predict():
    data = request.get_json()

    # 2. Convert input list to numpy array
    # We assume data["values"] is a flat list of 784 pixels or a 28x28 grid
    arr = np.array(data["values"])

    # 3. Preprocessing (Must match training!)
    # Reshape to (1, 28, 28, 1) -> (Batch, Height, Width, Channels)
    arr = arr.reshape(1, 28, 28, 1)

    # Normalize pixel values to 0-1 range (Critical for High Accuracy)
    arr = arr.astype("float32") / 255.0

    # 4. Make Prediction
    pred_probs = model.predict(arr)
    pred_label = np.argmax(pred_probs)
    confidence = float(np.max(pred_probs)) # Get confidence score

    return jsonify({
        "prediction": int(pred_label),
        "confidence": confidence
    })

if __name__ == "__main__":
    app.run(debug=True, port=5002)

